### ISSUE TITLE
Please, allow to create QueuesClient from Client directly

### ISSUE THREAD

**Issue by mihallis** [kubemq-io/kubemq-go#14]
Hi, i wanna use Ping() before using QueuesStream which is not available in QueuesClient.  Can you please add method bellow or Ping() on QueuesClient? At current state, i'm not allowed to create QueuesClient outside of package.

```go
// NewQueuesClient - create a new QueuesClient from client directly
func (c *Client) NewQueuesClient() *QueuesClient {
    return &QueuesClient{client: c}
}
```

Thanks.

**Comment by kubemq** [comment]
My assumption is you want to use the Ping to check connectivity to KubeMQ.
No need to do so.
The reason that there is no ping is because the queue stream is grpc
stream, which means that if there is no connection or dropping connection
you will get an error message.
Did we make the wrong assumption ?
Lior,

**Comment by mihallis** [comment]
Our reason for pinging broker before running app, is to test connection if really works as should. If not, we not able run an application. If this case is already handled by KubeMQ itself so it's not required.
